SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
SMALL_ASTEROID_POINTS = 5
MEDIUM_ASTEROID_POINTS = 3
LARGE_ASTEROID_POINTS = 1

PLAYER_RADIUS = 20
PLAYER_SPEED = 200
PLAYER_TURN_SPEED = 300
PLAYER_MAX_ACCELERATION = 2.5

SHOT_RADIUS = 5

INITIAL_EXPLOSION_PARTICLE_RADIUS = 5
EXPLOSION_AMOUNT_OF_PARTICLES = 8

DEFAULT_WEAPON_SHOOT_SPEED = 500
DEFAULT_WEAPON_SHOOT_COOLDOWN = 0.3

SHOTGUN_WEAPON_SHOOT_SPEED = 800
SHOTGUN_WEAPON_SHOOT_COOLDOWN = 0.5
SHOTGUN_WEAPON_SHOOT_COLOR = "yellow"

PIERCE_WEAPON_SHOOT_SPEED = 300
PIERCE_WEAPON_SHOOT_INITIAL_RADIUS = 8
PIERCE_WEAPON_SHOOT_MIN_RADIUS = 2
PIERCE_WEAPON_SHOOT_COOLDOWN = 2.0
PIERCE_WEAPON_SHOOT_COLOR = "red"

POWER_UP_RADIUS = 20
POWER_UP_SPAWN_RATE = 10 # seconds
POWER_UP_KINDS = 3
POWER_UP_SPEED_BOOST = 1.6
POWER_UP_SPEED_TIMER = 5
POWER_UP_SHIELD_TIMER = 5
POWER_UP_SHIELD_RADIUS = 30